image: node:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - build
  - staging

build:
  stage: build
  script:
    - npm install
    - unset CI
    - npm run build
  only:
        - master

staging:
    type: deploy
    stage: staging
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=$HEROKU_WEATHER --api-key=$HEROKU_API_KEY
    only:
        - master      
